name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-27"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL ="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiODM2MmIyNzAtN2NmYS00N2Q4LWEzMGItOWEyN2Y3Y2I2ZWNjIiwidGVuYW50X2lkIjoiMDI5ZjE3YWU5YWNiNTA4MGRkZTU3MGQ1MmIwMGE2NTVkNTRlYTc2M2NiM2M2OGNkOTEwNDdmZTMyNDhjYzcwNiIsImludGVybmFsX3NlY3JldCI6ImNiOTFiMjRmLWNhZmEtNDhiMy05YWE3LWEwMjYzZDdhMjI5MyJ9.VU6N4TTQHhzZMHg4VelStXOVUS3xrQLK4rdCO1L2N8Q"

JWT_SECRET="hello-world"